FROM node:8.7 as builder

WORKDIR /app
COPY . /app

RUN npm install

ENV NODE_ENV production

RUN npm run build

VOLUME /app

FROM busybox
MAINTAINER The Samoyeds <github.com/the-samoyeds>

COPY --from=builder /app /app
